sudo: required
language: node_js
node_js: "10"

env:
  - NODE_ENV=devnet
  - NODE_ENV=testnet
  - NODE_ENV=mainnet

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script: npm test

stages:
  - name: Lint
  - name: Test
