sudo: required
language: node_js
node_js: "10"

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script:
        - NODE_ENV=testnet npm test
        - NODE_ENV=devnet npm test
        - NODE_ENV=mainnet npm test

stages:
  - name: Lint
  - name: Test
