name: TomoChain Monitor
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'
jobs:
  TomoChain-Monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install
      - run: npm test
